name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  build:
    uses: PurgeBot-net/workflows/.github/workflows/build-service.yml@main
    with:
      package_name: purger
    secrets: inherit

  auto-label:
    if: github.event_name == 'pull_request'
    uses: PurgeBot-net/workflows/.github/workflows/auto-label.yaml@main
    secrets: inherit
